version: "3.8"

services:
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: unidthon
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 1234

  api_server:
    depends_on:
      - mysql
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command:
      - bash
      - -c
      - |
        ./wait-for-it.sh mysql:3306 -s -t 100
        uvicorn main:app --host 0.0.0.0 --reload

volumes:
  mysql-data:
